# Tomcat 配置
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 9030
  servlet:
    context-path: /emos-wx-api

# RestTemplate配置
remote:
  maxTotalConnect: 200
  maxConnectPerRoute: 100
  connectTimeout: 5000
  readTimeout: 30000

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 65261599Duck
      initial-size: 4
      max-active: 8
      min-idle: 2
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: root
      password: 65261599Duck

# Mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cunjun.personal.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    root: info
    com.cunjun.personal.emos.wx.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

# 应用程序配置
emos:
  jwt:
    #密钥
    secret: this-is-a-random-secret-for-emos-implemented-by-cunjun-1234567890
    #令牌过期时间（天）
    expire: 5
    #令牌缓存时间（天数）
    cache-expire: 10
  face:
    create-face-model-url: http://localhost:3000/create_face_model
    checkin-url: http://localhost:3000/checkin
  temp-image-folder: /Users/CunjunWang/Desktop/tmp
  checkPandemic: true
  pandemic-risk-url: http://m.%s.bendibao.com/news/yqdengji/?qu=%s